### ISSUE TITLE
Can I check whether user needs updating after executeVersionCheck() is called?

### ISSUE THREAD

**Issue by quvo** [misyobun/MSBVersionUpdater#1]
@naoto0101 Thank you very much for making such a good library. 
I'm using this now, but I have question about how to use this library.
I want to know the result whether a user needs updating or not, after `MSBVersionUpdater -> executeVersionCheck()` is called.

To know whether version up is necessary, I tried to use `isVersionUpNeeded ()` from other class.

**isVersionUpNeeded**
https://github.com/misyobun/MSBVersionUpdater/blob/master/msbversionupdater/src/main/java/jp/misyobun/lib/versionupdater/MSBVersionUpdater.java#L170 

However, the method is private. So, I can't use that. If there is a good way to solve the problem, please tell me.

**Comment by at-vinhhlb** [comment]
@quvo 
Excuse me, could you tell me how to upload Json file ( step one )?
I don't understand this step one, thank you!

**Comment by quvo** [comment]
@at-vinhhlb OK. Do you have any web applications to put JSON file on ? First step is just add a file on any path at the application.

**Comment by at-vinhhlb** [comment]
@quvo 
Thank you so much, I understood 💃  and already implement 👍 
Thank you!
